version: '2.0'
kind: assignment
type: ''
title: Title of the Assignment
description: Description of the Assignment
language: de
license: MIT
authors:
- name: NAME
  email: EMAIL@tugraz.at
  affiliation: TU Graz
maintainers:
- name: NAME
  email: EMAIL@tugraz.at
  affiliation: TU Graz
links:
- description: python
  url: https://www.python.org/
supportingMaterial:
- description: python
  url: https://www.python.org/
keywords:
- python
testDependencies: []
properties:
  studentSubmissionFiles:
  - 9.py
  additionalFiles: []
  testFiles: []
  studentTemplates: []
  executionBackendSlug: python-itp
