version: '1.0'
type: ProblemSet
title: Erstellen und Plotten eigener Funktionen
description: Description of the Problemset
language: en
license: MIT
authors:
- name: NAME
  email: EMAIL@tugraz.at
  affiliation: TU Graz
maintainers:
- name: NAME
  email: EMAIL@tugraz.at
  affiliation: TU Graz
links:
- description: python
  url: https://www.python.org/
supportingMaterial:
- description: python
  url: https://www.python.org/
keywords:
- python
testDependencies: []
properties:
  studentSubmissionFiles:
  - ./pskript.py
  - ./secansh.py
  - ./sgauss.py
  additionalFiles: []
  testFiles: []
  studentTemplates: []
